### PR TITLE
feat(dateinputtypein): type-in date input

### PR DESCRIPTION
**Pull request by angelac17**
Task: https://truework.atlassian.net/browse/SELF-131

Initial pass of a type-in Date Input. I'm using the native html date input here. Pros: gives us a smooth type in experience for free in for Chrome, Firefox. Cons: UX varies quite a lot depending on browser (in Safari and IE, it's just a blank input)

I explored [an alternative here](https://github.com/truework/forms/compare/angela/type-in-masked-date-input?expand=1), aiming to implement something closer to this example:

https://user-images.githubusercontent.com/59842325/127919504-970ba19b-ef54-48e8-b2af-2bcfffe1130d.mov

I think this alternative can give us one consistent experience across all browsers, but it gets a little tricky (I think we'll need to manipulate the cursor positioning?) and I can definitely explore this alternative further if we don't like the native one.

### Screenshots

Firefox:
- The calendar pops up automatically once the user clicks on this field. We can manually disable it, but that means we'd have to manually implement the clear button too. My thoughts are, it seems handy to keep the calendar here, pending design feedback.

https://user-images.githubusercontent.com/59842325/127917432-80cfc870-2006-40a7-8092-f1a55ebec8c4.mov

Chrome:
- We're able to hide the calendar picker on Chrome.

https://user-images.githubusercontent.com/59842325/127917501-d3733676-d810-4ad2-9453-90fc1b4b756c.mov

Safari:
- The native date picker is just a blank input field on Safari.

https://user-images.githubusercontent.com/59842325/127917511-d9959283-8ef4-4666-94e3-5f2b14a6e6d5.mov

IE (BrowserStack wasn't letting me type while recording, so took some screenshots):
- I'll need to look at the styling here.
- This one behaves a lot like the Safari experience, except it has a clear button.

IE_DatePicker_blank
IE_DatePicker_populated
IE_DatePicker_clear_button

### CODE REVIEW

**Comment by estrattonbailey** [comment]
Couple initial thoughts:
1. Can we re-use `Input` for this, just passing in `type='date'`?
2. Can we ensure that `max` and `min` attributes work for validation?
3. Can we deploy this to Netlify as well so people can test on branch deploys there?

Also, as of Safari 14.1 it should have a date picker, that version was just released a couple months ago. Luckily Apple kinda forces people to update eventually, so within 6 months we should see the majority of macOS users on that version.

**Comment by annchensf** [comment]
questions..
- Firefox: Can you type in this datepicker? hard to tell in the video - does it force you to use the calendar?
- Safari/IE- is there a way to include a placeholder?
- what does mobile look like? :) 
- And, can you help me understand, are these options solely related to enabling the native calendar UI? For example, if we decide to forgo the calendar ui entirely, would all browsers just be consistent?

**Comment by nickbytes** [comment]
> Also, as of Safari 14.1 it should have a date picker, that version was just released a couple months ago. Luckily Apple kinda forces people to update eventually, so within 6 months we should see the majority of macOS users on that version.

@estrattonbailey what will happen for users who haven't updated?

**Comment by angelac17** [comment]
Here's a Netlify preview link: https://deploy-preview-28--truework-forms.netlify.app/?path=/story/base--dateinput 

Thanks Eric for the suggestion :)

**Comment by angelac17** [comment]
> Can we re-use Input for this, just passing in type='date'?

Yes we can, good point! I like this option a lot, it'll save us from implementing a new component. It'll look a little different than the original date input which I am fine with. Including a recording for @annchensf:

https://user-images.githubusercontent.com/59842325/127936700-fa726c3b-4343-4eb1-a609-090d31363630.mov

**Comment by angelac17** [comment]
> Firefox: Can you type in this datepicker? hard to tell in the video - does it force you to use the calendar? 

Yes you can type, you aren't forced to use the calendar. I just added a preview link for this, feel free to play around with it in Firefox if that will be helpful! 

> Safari/IE- is there a way to include a placeholder? 

Good question, I'm not sure if there was anything I overlooked but I don't think I can display a placeholder only on specific browsers. I had tried some tricks to add a placeholder, but since Chrome already shows the "mm/dd/yyyy" by default, there were two copies of that showing 🙁 

> Can you help me understand, are these options solely related to enabling the native calendar UI? For example, if we decide to forgo the calendar ui entirely, would all browsers just be consistent? 

Thanks for pushing me to clarify, I don't think I did a good job laying out my thoughts. These are the options related to using the native date input. If we want the same experience across browsers, I think the only way to do so might be to implement our own date input, which I wasn't sure was worth it if the native input already worked pretty well. I'm realizing now that I was a little short-sighted with that call since this only works well on Chrome/Firefox.

**Comment by angelac17** [comment]
closing for now in favor of #29.

**Pull request closed without merging**
